### ISSUE TITLE
Data syncing timeout happens almost always

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-cli#25]
When trying to upload something (either with the `upload` command or with the `feed upload` command) I almost always get  `data syncing timeout` timeout error. When trying the second time it always work. Because of this the CLI upload feels buggy.

We discussed this issue with @Cafe137 and the simple but crude fix could be to increase the sync timeout. A more sophisticated solution could be that while the values are changing restart the timeout from 0.

**Comment by Cafe137** [comment]
In `waitForFileSynced` we are testing `tag.synced`. When running a local node for development in standalone mode, that stays stuck (sometimes 0, sometimes 1) forever. `tag.processed` works as intended and reaches `tag.total` in a short time.

I assume changing from `synced` to `processed` is not a good option though, since that is not a proper check of the upload status.

I have added the timeout restart: https://github.com/ethersphere/swarm-cli/commit/79a8f251368559d64802cc49648060dc6a63cd1a

**Comment by Cafe137** [comment]
Related: https://github.com/ethersphere/beekeeper/pull/112
