### ISSUE TITLE
Feed upload /bzz reference only works with directories, not single files

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/swarm-cli#30]
Steps to reproduce: 

- Upload a **single file** with `feed upload`
- Open Feed Manifest URL (`/bzz`)
- Receive `{ "message": "Not Found", "code": 404 }`

This works with directories when `--index-document` is specified. When `--index-document` is NOT specified, error is `ERR_TOO_MANY_REDIRECTS`, but that is off topic.

Note: In all 3 scenarios described above, the `/feeds/{owner}/{topic}` endpoint returns a JSON object with a `reference` property.

Possible solution is to modify `bee-js` so that it allows passing `indexDocument` in `uploadFile` if the core bee API permits it. In that case the index document should be auto-filled by `swarm-cli` to be the same as the uploaded file. This raises a question though: how would `feed update` work, since the file name is unknown by then.

**Comment by agazso** [comment]
Instead of modifying `uploadFile` you are supposed to use `uploadFiles` and passing only a single file in an array and there you can specify the `indexDocument` as well.

In the case of `feed update` it is not necessary to do this because it is a more low-level primitive that could allow updating the feed with different kind of data as well. We can assume that if someone is using it either knows what they are doing or they would use the plain `upload` command which would upload the single file with the `indexDocument` set already.
